# auto generate tailwind css
name: Generate Tailwind CSS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npx tailwindcss -c ./tailwind.config.js -i style/input.css -o style/output.css
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: automatic tidy up code
          branch: ${{ github.head_ref }}
